"""tambah deleted_at untuk hapus lunak

Revision ID: 3433c3739100
Revises: c58c8eb39317
Create Date: 2026-08-27 04:02:12.096371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel memakai tipe kolomnya sendiri (mis. AutoString), yang muncul di
# berkas migrasi hasil autogenerate. Submodulnya diimpor eksplisit karena
# `import sqlmodel` saja tidak membuat sqlmodel.sql dikenali.
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3433c3739100'
down_revision: Union[str, Sequence[str], None] = 'c58c8eb39317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lettertype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lettertype', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
