"""tabel delivery (kirim surat)

Revision ID: 92dac5e70cd0
Revises: 32aafb646104
Create Date: 2026-09-04 14:16:46.080679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel memakai tipe kolomnya sendiri (mis. AutoString), yang muncul di
# berkas migrasi hasil autogenerate. Submodulnya diimpor eksplisit karena
# `import sqlmodel` saja tidak membuat sqlmodel.sql dikenali.
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '92dac5e70cd0'
down_revision: Union[str, Sequence[str], None] = '32aafb646104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Tabel `delivery` (Stage B4): satu upaya kirim satu-atau-lebih PDF ke satu
    kontak lewat satu channel. Trigger-agnostic — `job_id` menautkan ke batch
    generate yang memicu, nullable supaya portal mahasiswa nanti jadi pemicu
    lain. `send_batch_id` mengelompokkan satu aksi "Kirim" (bukan FK).

    Tabel baru: batch mode untuk index aman di sini (tidak ada data / constraint
    lama yang bisa hilang).
    """
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_type_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', name='deliverychannel'), nullable=False),
    sa.Column('send_batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recipient_contact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachment_names', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'auth_expired', name='deliverystatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['letter_type_id'], ['lettertype.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_letter_type_id'), ['letter_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_send_batch_id'), ['send_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_unit_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_send_batch_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_letter_type_id'))

    op.drop_table('delivery')
    # ### end Alembic commands ###
