"""skema awal letter type

Revision ID: c58c8eb39317
Revises: 
Create Date: 2026-08-27 02:45:27.165520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel memakai tipe kolomnya sendiri (mis. AutoString), yang muncul di
# berkas migrasi hasil autogenerate. Submodulnya diimpor eksplisit karena
# `import sqlmodel` saja tidak membuat sqlmodel.sql dikenali.
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c58c8eb39317'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lettertype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lettertype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lettertype_slug'), ['slug'], unique=True)

    op.create_table('letterfield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'date', 'number', name='fieldtype'), nullable=False),
    sa.Column('level', sa.Enum('batch', 'recipient', name='fieldlevel'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['letter_type_id'], ['lettertype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letterfield')
    with op.batch_alter_table('lettertype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lettertype_slug'))

    op.drop_table('lettertype')
    # ### end Alembic commands ###